# Generated by Django 4.2.9 on 2025-02-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='mainimage',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
