# Generated by Django 4.2.9 on 2025-02-21 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_mainimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='amount',
        ),
    ]
