# Generated by Django 4.2.9 on 2025-03-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='instock',
            field=models.BooleanField(default=True),
        ),
    ]
