# Generated by Django 4.2.9 on 2025-01-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesainvoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesainvoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mpesainvoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
