# Generated by Django 4.2.9 on 2025-02-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('location', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, default=True, editable=False, max_digits=10)),
            ],
        ),
    ]
