# Generated by Django 4.2.9 on 2025-02-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0001_initial'),
        ('purchaseitem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='items',
            field=models.ManyToManyField(related_name='purchases', to='purchaseitem.purchaseitem'),
        ),
    ]
