# Generated by Django 4.2.9 on 2025-02-20 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='items',
            new_name='purchaseitems',
        ),
    ]
