# Generated by Django 4.2.9 on 2025-02-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_rename_items_purchase_purchaseitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='transaction_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
