# Generated by Django 4.2.9 on 2025-02-22 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_purchase_transaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='transaction_date',
            new_name='dated',
        ),
    ]
