# Generated by Django 4.2.9 on 2025-02-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_rename_transaction_date_purchase_dated'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='round',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
