# Generated by Django 4.2.9 on 2025-01-05 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CelebService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateofcreation', models.DateField(auto_now_add=True, null=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('celebid', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='celebservices', to=settings.AUTH_USER_MODEL)),
                ('serviceid', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='celebservices', to='service.service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
