# Generated by Django 4.2.9 on 2025-01-05 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('celebservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateofcreation', models.DateField(auto_now_add=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('auto_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('CANCELED', 'Canceled'), ('COMPLETED', 'Completed'), ('RESCHEDULED', 'Rescheduled'), ('SCHEDULED', 'Scheduled'), ('DONEREQUESTED', 'Donerequested')], default='PENDING', max_length=15)),
                ('rescheduled_date', models.DateTimeField(blank=True, null=True)),
                ('canceled_date', models.DateTimeField(blank=True, null=True)),
                ('customer_complete_celeb_remarks', models.TextField(blank=True, default='', null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('invoice_id', models.CharField(default='None', max_length=255)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('refund_Request', models.BooleanField(default=False)),
                ('refunded', models.BooleanField(default=False)),
                ('refundedOn', models.CharField(blank=True, max_length=255, null=True)),
                ('client_Reschedule_Request', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complete_requested_by_celeb', models.BooleanField(default=False)),
                ('customer_complete_request_accepted', models.BooleanField(default=False)),
                ('customer_reject_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('is_shout_out_video_recorded', models.BooleanField(default=False)),
                ('shoutout_video', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('shoutoutdescription', models.CharField(blank=True, default=None, max_length=655, null=True)),
                ('withdraw_request', models.BooleanField(default=False)),
                ('withdrawn', models.BooleanField(default=False)),
                ('withdrawn_date', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancellencations_as_user', to=settings.AUTH_USER_MODEL)),
                ('celeb', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='payments_as_celeb', to=settings.AUTH_USER_MODEL)),
                ('celebservice', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='celebservice.celebservice')),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='payments_as_client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
