# Generated by Django 4.2.9 on 2025-01-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='clientamount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='request',
            name='companyamount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='request',
            name='state',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CANCELED', 'Canceled'), ('COMPLETED', 'Completed'), ('RESCHEDULED', 'Rescheduled'), ('SCHEDULED', 'Scheduled'), ('DONEREQUESTED', 'Donerequested'), ('WITHDRAWREQUEST', 'Withdrawrequest'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=15),
        ),
    ]
