# Generated by Django 4.2.9 on 2025-01-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_request_clientamount_request_companyamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='state',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CANCELED', 'Canceled'), ('RESCHEDULED', 'Rescheduled'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('DONEREQUESTED', 'Donerequested'), ('WITHDRAWREQUEST', 'Withdrawrequest'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=15),
        ),
    ]
