# Generated by Django 4.2.9 on 2025-01-25 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_alter_request_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(default='', max_length=50)),
                ('device_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('tracking_id', models.CharField(default='', max_length=100, unique=True)),
                ('batch_reference', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('status', models.CharField(default='', max_length=100)),
                ('status_code', models.CharField(default='', max_length=50)),
                ('nonce', models.CharField(default='', max_length=50)),
                ('wallet_id', models.CharField(default='', max_length=50)),
                ('wallet_label', models.CharField(default='', max_length=100)),
                ('can_disburse', models.BooleanField(default=True)),
                ('currency', models.CharField(default='', max_length=10)),
                ('wallet_type', models.CharField(default='', max_length=50)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('wallet_updated_at', models.DateTimeField()),
                ('charge_estimate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount_estimate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('transactions_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawMpesaPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=50)),
                ('status_code', models.CharField(default='', max_length=50)),
                ('request_reference_id', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('account', models.CharField(default='', max_length=20)),
                ('id_number', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('bank_code', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('narrative', models.TextField(blank=True, default='', null=True)),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='request.mpesatransfer')),
            ],
        ),
    ]
