# Generated by Django 4.2.9 on 2025-01-25 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('request', '0004_mpesatransfer_withdrawmpesapaymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransfer',
            name='celeb',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='MpesaTransfer_Celeb', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='withdrawmpesapaymenttransaction',
            name='celeb',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='WithdrawMpesaPaymentTransaction_Celeb', to=settings.AUTH_USER_MODEL),
        ),
    ]
