# Generated by Django 4.2.9 on 2025-02-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_alter_mpesatransfer_celeb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='state',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CANCELED', 'Canceled'), ('COMPLETED', 'Completed'), ('WITHDRAWREQUEST', 'Withdrawrequest'), ('WITHDRAWN', 'Withdrawn'), ('RESCHEDULED', 'Rescheduled'), ('SCHEDULED', 'Scheduled')], default='PENDING', max_length=15),
        ),
    ]
