# Generated by Django 4.2.9 on 2025-02-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='facebook_page',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='instagram_page',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='other_page',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='tiktok_page',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='youtube_page',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='biotext',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
