# Generated by Django 4.2.9 on 2025-01-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='biotext',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
