# Generated by Django 4.2.9 on 2025-02-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0002_alter_appuser_biotext'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='facebook_page',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='instagram_page',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='tiktok_page',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
