# Generated by Django 4.2.9 on 2025-02-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0003_appuser_facebook_page_appuser_instagram_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='other_page',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='youtube_page',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
