# Generated by Django 4.2.9 on 2025-03-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandleClassBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('class_type', models.CharField(choices=[('Online Class', 'Online Class'), ('Private In-Person Class', 'Private In-Person Class')], max_length=50)),
                ('available_date_time', models.CharField(max_length=200)),
                ('participants', models.PositiveIntegerField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candle Class Booking',
                'verbose_name_plural': 'Candle Class Bookings',
            },
        ),
    ]
