# Generated by Django 4.2.9 on 2025-03-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candleclassbookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candleclassbooking',
            old_name='available_date_time',
            new_name='availableDateTime',
        ),
        migrations.RenameField(
            model_name='candleclassbooking',
            old_name='class_type',
            new_name='classType',
        ),
        migrations.RenameField(
            model_name='candleclassbooking',
            old_name='event_type',
            new_name='eventType',
        ),
        migrations.RenameField(
            model_name='candleclassbooking',
            old_name='full_name',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='candleclassbooking',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='candleclassbooking',
            old_name='special_requests',
            new_name='specialRequests',
        ),
    ]
