# Generated by Django 4.2.9 on 2025-03-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candleclassbookings', '0002_rename_available_date_time_candleclassbooking_availabledatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candleclassbooking',
            name='participants',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
