# Generated by Django 4.2.9 on 2025-03-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candleclassbookings', '0003_alter_candleclassbooking_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candleclassbooking',
            name='participants',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
