# Generated by Django 4.2.9 on 2025-03-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candleclassbookings', '0004_alter_candleclassbooking_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='candleclassbooking',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
